name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run a simple test
        run: |
          echo "GitHub Actions ist erfolgreich konfiguriert!"
          echo "Aktueller Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}" 